### PR TITLE
Update to derive_more 0.99.1 and syn, quote, proc_macro2 1.0

### PR DESCRIPTION
**Pull request by Robbepop**
- Update to `derive_more` version `0.99.1`
- ~~Update `derive` sub-crate to `syn`, `quote`, `proc_macro2` to version `1.0`~~
- `Cargo.lock` is no longer git-ignored

### CODE REVIEW

**Review by xlc — APPROVED** [review]
CI is failling

**Comment by Robbepop** [comment]
> CI is failling

@xlc thanks, fixed

**Comment by xlc** [comment]
Conflicts needs resolving.

**Comment by Robbepop** [comment]
> Conflicts needs resolving.

Ahh, ... I made a mistake and wasn't aware that this has been fixed in `master` already because of it. Have resolved conflicts as far as I can tell. CI is failing because of `clippy` missing.

**Pull request merged**
