### PR TITLE
Fully no_std support

### LINKED ISSUE #7: Fully support no_std environments
required for wasm compatibility

### PR DESCRIPTION
**Pull request by shaunxw**
Closes #7

### CODE REVIEW

**Review by Robbepop — COMMENTED** [review]
LGTM

Has this been tested already to properly work with `no_std` crates?

**Comment by shaunxw** [comment]
@Robbepop I'm working on testing different cases, meanwhile fixing other std preludes imports, once finished I'll remove the `[WIP]` in title. (Seems I'd better use the draft PR next time and clarify in description :] )

**Comment by shaunxw** [comment]
Update: Added `derive_tests_no_std` tests crate for `no_std` env.

**Comment by Robbepop** [comment]
What stops this from being merged?

**Comment by shaunxw** [comment]
@Robbepop `cargo check --all` was complaining about duplicate lang items, because that `derive_tests_no_std`(which introduce custom lang items to test `no_std` env) and other crates share the same workspace. I've just fixed it.

It's good to be merged now. :)

**Pull request merged**
