### PR TITLE
Simplification of type-metadata traits and Registry

### PR DESCRIPTION
**Pull request by Robbepop**
I was trying to use the type registry from within the new upcoming `ink-abi` crate but had some problems. The work made in this PR is trying to resolve them and improve upon general usability of the `type-metadata` crate.
I will undraft this PR once I am done with the integration.

The current "limitation" for the reworking is that the algorithm differentiates between `T` and `Box<T>` or between `String` and `str`. This however, should be easy to fix if we are sure to want the former behaviour of aligning types like `Box<T>` to `T` etc.

### CODE REVIEW

**Comment by Robbepop** [comment]
Just fixed the commit history of this PR. Should be reviewable now. However, I still have to fix the remaining tests before I will un-draft it.

**Review by xlc — COMMENTED** [review]
Looks good. Needs some formatting to ensure consistent whitespaces.

**Comment by shaunxw** [comment]
LGTM. Not related to this PR but I think we could add an `.editorconfig` file to provide some default formatting consistency.

**Comment by Robbepop** [comment]
Thanks for your reviews.

> LGTM. Not related to this PR but I think we could add an `.editorconfig` file to provide some default formatting consistency.

That is a good idea!

Would it be okay if I update the rustfmt.toml file somehow?
I think the standard Rust formatting could be improved and we do not have to stick to Substrate formatting anyway since this project is standalone.

**Comment by Robbepop** [comment]
Added README, removed no longer needed code and types and applied rustfmt. Ready for merge.

**Comment by Robbepop** [comment]
Added `no_std` support to close https://github.com/type-metadata/type-metadata/issues/7.

**Comment by shaunxw** [comment]
> Would it be okay if I update the rustfmt.toml file somehow?

Please feel free to update it :]

The `no_std` support seems not ready yet. I tried to create an `no_std` example using `type-metadata` for verification and it doesn't work. We might need to fix all the types, crates, and traits usage which does not exit in `no_std` preludes, for instance `Vec`, `vec!`.

One possible solution is to use a wrapper to hide the difference between `std` and `no_std` imports, just like the [`sr_std`](https://github.com/paritytech/substrate/tree/master/core/sr-std) impl(or possibly use `sr-std` as a dependency). Maybe it's better to do the full `no_std` support in another PR?

**Comment by Robbepop** [comment]
> > Would it be okay if I update the rustfmt.toml file somehow?
> 
> Please feel free to update it :]
> 
> The `no_std` support seems not ready yet. I tried to create an `no_std` example using `type-metadata` for verification and it doesn't work. We might need to fix all the types, crates, and traits usage which does not exit in `no_std` preludes, for instance `Vec`, `vec!`.
> 
> One possible solution is to use a wrapper to hide the difference between `std` and `no_std` imports, just like the [`sr_std`](https://github.com/paritytech/substrate/tree/master/core/sr-std) impl(or possibly use `sr-std` as a dependency). Maybe it's better to do the full `no_std` support in another PR?

Let's do full `no_std` support in another PR. This one is already doing so much.
I am against depending on anything from substrate. This should be standalone since it can be.
I think this crate is small enough to not need such a general shim as another dependency.

**Comment by Robbepop** [comment]
> > > Would it be okay if I update the rustfmt.toml file somehow?
> > 
> > 
> > Please feel free to update it :]
> > The `no_std` support seems not ready yet. I tried to create an `no_std` example using `type-metadata` for verification and it doesn't work. We might need to fix all the types, crates, and traits usage which does not exit in `no_std` preludes, for instance `Vec`, `vec!`.
> > One possible solution is to use a wrapper to hide the difference between `std` and `no_std` imports, just like the [`sr_std`](https://github.com/paritytech/substrate/tree/master/core/sr-std) impl(or possibly use `sr-std` as a dependency). Maybe it's better to do the full `no_std` support in another PR?
> 
> Let's do full `no_std` support in another PR. This one is already doing so much.

**Comment by Robbepop** [comment]
Never, intended to close this, sorry ...

**Comment by shaunxw** [comment]
Merged :]

**Pull request merged**
